### ISSUE TITLE
Integrate vision data

### ISSUE THREAD

**Issue by WesleyJ-128** [first95/FRC2023#4]
Use the WPILib PoseEstimator to integrate vision data into the odometry system.  Ideally the vision data will be used to "seed" odometry on boot/enable/match start, so the robot can be plonked anywhere in the community for auto.  May also be useful for autoleveling.

**Comment by 0NotApplicable0** [comment]
LimeLight subsystem created and botpose data is being fetched, next steps:
 - Create getter for botpose
 - Fetch botpose data from within odom system and set as seed

**Comment by WesleyJ-128** [comment]
I wasn't using a subsytem— the drivebase subsytem can't access any other subsytems, and odometry is handled by the drivebase subsystem.

**Comment by 0NotApplicable0** [comment]
The way I was thinking we could do it would be to have a public function called "setOdometry" which could have vision data as arguments. Also, with the subsystems, we isolate vision components like `NetworkTableInstance.getDefault().getTable("limelight");` to actual vision systems to handle.

Keeps the separation of subsystems, drive does drive, vision does vision.

We then can call this function from a command using the LimeLight subsystem. This way we only update when a valid vision target is acquired and the command is called.

I'm not sure what happens if we pass in null or 0s to SwerveDrivePoseEstimator will do. The described above way will prevent that. `getVisionPose().toPose2d()` might throw a null ptr exception because of 
```    
if (visionData.getEntry("tv").getDouble(0) == 0) {
      return null;
 }
```
Is returning null and toPose2d() doesn't exist on null.

**Comment by 0NotApplicable0** [comment]
This was misleading: 'Fetch botpose data from within odom system and set as seed' my bad.

**Comment by 0NotApplicable0** [comment]
This is what I was thinking: [12dc841924043c1fb8ad20a85a1d257aad87b5da
](https://github.com/first95/FRC2023/commit/12dc841924043c1fb8ad20a85a1d257aad87b5da)

A generic updateOdom function that can be passed any Pose2D, doesn't have to be vision data could be from other sources not just one set limelight.

**Comment by WesleyJ-128** [comment]
The SearchForTargets command requires the drivebase, so it will interrupt the drivebase's default command (driving).  Only one command can run at a time for each subsytem.

**Comment by 0NotApplicable0** [comment]
I suppose that's true, and I don't think WPILib has a way to lock subsystems like mutexs. 

My only concern is what if we want to provide different data to update odom. Either a separate camera or LiDAR, I guess we won't be using LiDAR, but what about another camera?

Make the subsystem public via RobotContainer, control what camera via a constant?
